version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html